package com.example.stunningweather.models

class Hour(
    val time_epoch: Int = -1,
    val time: String = "-1",
    val temp_c: Double = -1.0,
    val temp_f: Double = -1.0,
    val is_day: Int = -1,
    val condition: Condition = Condition(),
    val wind_mph: Double = -1.0,
    val wind_kph: Double = -1.0,
    val wind_degree: Int = -1,
    val wind_dir: String = "-1",
    val pressure_mb: Int = -1,
    val pressure_in: Double = -1.0,
    val precip_mm: Double = -1.0,
    val precip_in: Double = -1.0,
    val humidity: Int = -1,
    val cloud: Int = -1,
    val feelslike_c: Double = -1.0,
    val feelslike_f: Double = -1.0,
    val windchill_c: Double = -1.0,
    val windchill_f: Double = -1.0,
    val heatindex_c: Double = -1.0,
    val heatindex_f: Double = -1.0,
    val dewpoint_c: Double = -1.0,
    val dewpoint_f: Double = -1.0,
    val will_it_rain: Int = -1,
    val chance_of_rain: Int = -1,
    val will_it_snow: Int = -1,
    val chance_of_snow: Int = -1,
    val vis_km: Double = -1.0,
    val vis_miles: Double = -1.0,
    val gust_mph: Double = -1.0,
    val gust_kph: Double = -1.0,
    val uv: Double = -1.0
)